name: TESTLINKS

on:
  push:
    branches:
      - "master"
      - "feat-*"
      - "maintenance-*"
      - "release-*"
  schedule:
    - cron: "30 11 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 16.x

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test-links
        env:
          DISABLE_PROXY: true
